services:
  api:
    build:
      context: .
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1
    network_mode: "host"
    volumes:
      - .:/app

  cache:
    image: valkey/valkey
    ports:
      - "6379:6379"

  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
